name: Build Branch
on:
  workflow_dispatch:
    inputs:
      driver_revision:
        description: "Driver revision to use, if not the latest"
        required: false
      clobber:
        description: "Whether to build the browser from scratch"
        type: boolean
        required: false

jobs:
  build:
    name: Trigger build run on current branch
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@effa99fe9dc68518c77d0e7c00879f6599714d39
        with:
          authkey: ${{ secrets.TAILSCALE_API_KEY }}
          version: "1.26.0"
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-test-branch
        env:
          BUILD_TEST_AUTHORIZATION: ${{ secrets.BUILD_TEST_AUTHORIZATION }}
          BUILD_TEST_HOSTNAME: build-server.replay.prod
          BUILD_TEST_PORT: ${{ secrets.BUILD_TEST_PORT }}
          BUILD_TEST_INSECURE: ${{ secrets.BUILD_TEST_INSECURE }}
          INPUT_DRIVER_REVISION: ${{ github.event.inputs.driver_revision }}
          INPUT_CLOBBER: ${{ github.event.inputs.clobber }}
          BUILD_ONLY: 1
