name: Build/Test
on:
  workflow_dispatch:
  push:
    branches:
      - webreplay-release

jobs:
  build-test:
    name: Trigger build/test run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-test
        env:
          BUILD_TEST_AUTHORIZATION: ${{ secrets.BUILD_TEST_AUTHORIZATION }}
          BUILD_TEST_HOSTNAME: ${{ secrets.BUILD_TEST_HOST }}
          BUILD_TEST_PORT: ${{ secrets.BUILD_TEST_PORT }}
          BUILD_TEST_INSECURE: ${{ secrets.BUILD_TEST_INSECURE }}
